### ISSUE TITLE
On styling links

### ISSUE THREAD

**Issue by mbesser** [mbesser/mbesser.github.io#18]
- often struggled with global link styling attached to the `a { … }`
- had to override regularly for navigation links, links styled as buttons etc.
- combination of `:not(s)`pseudo selector and attribute selector allows to target common links that don't have a class applied to them
- assuming that no classes are used on common links

``` scss
a:not([class]) {
  border-bottom: 1px dotted currentColor;
  color: $color-link;
  transition: color 250ms ease-out;

  &:hover {
    color: $color-link-hover;
    text-decoration: none;
    transition: color 250ms ease-in;
  }
}
```
